#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH="/home/shmpwk/gps_ws/src/gps/src/gps_agent_pkg/devel:$CMAKE_PREFIX_PATH"
export LD_LIBRARY_PATH="/opt/ros/melodic/share/euslisp/jskeus/eus//Linux64/lib:/home/shmpwk/catkin_ws/devel/lib:/opt/ros/melodic/lib:/opt/ros/melodic/share/euslisp/jskeus/eus//Linux64/lib:/opt/ros/melodic/share/euslisp/jskeus/eus//Linux64/lib:/opt/ros/melodic/share/euslisp/jskeus/eus//Linux64/lib:/opt/ros/melodic/share/euslisp/jskeus/eus//Linux64/lib:/opt/ros/melodic/share/euslisp/jskeus/eus//Linux64/lib:/opt/ros/melodic/share/euslisp/jskeus/eus//Linux64/lib:/opt/ros/melodic/share/euslisp/jskeus/eus//Linux64/lib:/opt/ros/melodic/share/euslisp/jskeus/eus//Linux64/lib:/opt/ros/melodic/share/euslisp/jskeus/eus//Linux64/lib:/opt/ros/melodic/share/euslisp/jskeus/eus//Linux64/lib:/home/shmpwk/.mujoco/mujoco200/bin:/home/shmpwk/.mujoco/mujoco200/bin:/home/shmpwk/gps_ws/src/build/lib:/home/shmpwk/gps_ws/src/gps/build/lib:/home/shmpwk/gps_ws/src/gps/build/lib"
export PATH="/opt/ros/melodic/share/euslisp/jskeus/eus//Linux64/bin:/opt/ros/melodic/bin:/opt/ros/melodic/share/euslisp/jskeus/eus//Linux64/bin:/opt/ros/melodic/share/euslisp/jskeus/eus//Linux64/bin:/opt/ros/melodic/share/euslisp/jskeus/eus//Linux64/bin:/opt/ros/melodic/share/euslisp/jskeus/eus//Linux64/bin:/opt/ros/melodic/share/euslisp/jskeus/eus//Linux64/bin:/opt/ros/melodic/share/euslisp/jskeus/eus//Linux64/bin:/opt/ros/melodic/share/euslisp/jskeus/eus//Linux64/bin:/opt/ros/melodic/share/euslisp/jskeus/eus//Linux64/bin:/opt/ros/melodic/share/euslisp/jskeus/eus//Linux64/bin:/opt/ros/melodic/share/euslisp/jskeus/eus//Linux64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
export ROSLISP_PACKAGE_DIRECTORIES="/home/shmpwk/gps_ws/src/gps/src/gps_agent_pkg/devel/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/shmpwk/gps_ws/src/gps/src/gps_agent_pkg:/home/shmpwk/catkin_ws/src/jsk-ros-pkg/jsk_robot/jsk_aero_robot/aeroeus:/home/shmpwk/catkin_ws/src/jsk-ros-pkg/jsk_robot/jsk_baxter_robot/baxtereus:/home/shmpwk/catkin_ws/src/jsk-ros-pkg/jsk_robot/jsk_fetch_robot/fetcheus:/home/shmpwk/catkin_ws/src/jsk-ros-pkg/jsk_robot/jsk_aero_robot/jsk_aero_startup:/home/shmpwk/catkin_ws/src/jsk-ros-pkg/jsk_robot/jsk_baxter_robot/jsk_baxter_startup:/home/shmpwk/catkin_ws/src/jsk-ros-pkg/jsk_robot/jsk_baxter_robot/jsk_baxter_desktop:/home/shmpwk/catkin_ws/src/jsk-ros-pkg/jsk_robot/jsk_baxter_robot/jsk_baxter_web:/home/shmpwk/catkin_ws/src/jsk-ros-pkg/jsk_robot/jsk_fetch_robot/jsk_fetch_diagnosis:/home/shmpwk/catkin_ws/src/jsk-ros-pkg/jsk_robot/jsk_fetch_robot/jsk_fetch_startup:/home/shmpwk/catkin_ws/src/jsk-ros-pkg/jsk_robot/jsk_naoqi_robot/jsk_nao_startup:/home/shmpwk/catkin_ws/src/jsk-ros-pkg/jsk_robot/jsk_naoqi_robot/jsk_pepper_startup:/home/shmpwk/catkin_ws/src/jsk-ros-pkg/jsk_robot/jsk_pr2_robot/jsk_pr2_calibration:/home/shmpwk/catkin_ws/src/jsk-ros-pkg/jsk_robot/jsk_pr2_robot/jsk_pr2_startup:/home/shmpwk/catkin_ws/src/jsk-ros-pkg/jsk_robot/jsk_robot:/home/shmpwk/catkin_ws/src/jsk-ros-pkg/jsk_robot/jsk_robot_common/jsk_robot_startup:/home/shmpwk/catkin_ws/src/jsk-ros-pkg/jsk_robot/jsk_robot_common/jsk_robot_utils:/home/shmpwk/catkin_ws/src/jsk-ros-pkg/jsk_robot/jsk_naoqi_robot/naoqieus:/home/shmpwk/catkin_ws/src/jsk-ros-pkg/jsk_robot/jsk_naoqi_robot/naoeus:/home/shmpwk/catkin_ws/src/jsk-ros-pkg/jsk_robot/jsk_naoqi_robot/peppereus:/home/shmpwk/catkin_ws/src/jsk-ros-pkg/jsk_robot/jsk_naoqi_robot/jsk_201504_miraikan:/home/shmpwk/catkin_ws/src/jsk-ros-pkg/jsk_robot/jsk_pr2_robot/pr2_base_trajectory_action:/home/shmpwk/catkin_ws/src/jsk-ros-pkg/jsk_robot/jsk_pr2_robot/jsk_pr2_desktop:/home/shmpwk/catkin_ws/src/jsk-ros-pkg/jsk_robot/jsk_robot_common/roseus_remote:/opt/ros/melodic/share"